### ISSUE TITLE
people can declare war on weak claim in new beta version!

### ISSUE THREAD

**Issue by ClaudeWithYouForever** [zijistark/EMF#674] opened 2020-03-05 12:25 UTC

**Comment by zijistark** [comment] 2020-03-05 14:17
Do you mean that rulers are able to declare war to press their weak claim on a title when they should not be able to do so?

Can you please provide some more context? This would be helpful:
- Was the defending ruler uncrowned?
- Was the defending ruler in a regency?
- Was the defending ruler a woman, and did the claimed title have Agnatic or Agnatic-Cognatic Succession?
- Was the attacker a pretender to the claimed title?
- Was the claimed title already being contested by some other ongoing war? Note that revolts / civil wars usually count for contesting the primary title of their rightful liege (before the war).

**Comment by ClaudeWithYouForever** [comment] 2020-03-06 00:06
I can declare war on all weak claim targets regardless of all conditions and I started this archieve with beta 2.21. It was ok until I changed with beta 3.4.The war against conditions will not bring any result whatever I win or not.

**Comment by zijistark** [comment] 2020-03-06 00:57
Looks like this was caused by a bug that I fixed a few moments ago. Not related specifically to the CB, but a cascading syntax error. It's now resolved in the 2020-03-05 beta, which I've pushed as of a moment ago.

**Closed as completed** 2020-03-06 00:58 UTC
Labels: bug
